### ISSUE TITLE
[BUG] FATAL EXCEPTION: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasTransport(int)' on a null object reference

### ISSUE THREAD

**Issue by kaikli** [guardianproject/orbot-android#1085]
**Describe the Bug**
Only found this exception in LogFox.

**Smartphone (please complete the following information):**
- Device: Pixel 6a
- OS: Android 14
- Version: v17.0.0-RC-1-tor.0.4.7.11 (fdroid version)

**Crash Logs (Advanced)**
```
FATAL EXCEPTION: ConnectivityThread
Process: org.torproject.android, PID: 23891
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasTransport(int)' on a null object reference
	at org.torproject.android.service.OrbotService$1.onLost(OrbotService.java:551)
	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:4271)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by bitmold** [comment]
Closing this, this null case has been handled in the code for a while now 

```java
            var netCap = connMgr.getNetworkCapabilities(connMgr.getActiveNetwork());
            if (netCap != null)
                mHasWifi = netCap.hasTransport(NetworkCapabilities.TRANSPORT_WIFI);
            else
                mHasWifi = false;
        }
```
