### ISSUE TITLE
Crash when trying to paste custom bridge

### ISSUE THREAD

**Issue by Thewisem** [guardianproject/orbot-android#472]
Device: Samsung Galaxy Tab A SM P555
OS: Version 7.1.1 Nougat
Issue
When i click on custom bridge and reach the next page, it crashes after reaching for some time.
Is this reproducable? Yes
Thought it was a one off thing. But no, it craahed all the time.

**Comment by Thewisem** [comment]
FATAL EXCEPTION: main
Process: org.torproject.android, PID: 31782
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.Editor$SelectionModifierCursorController.isDragAcceleratorActive()' on a null object reference
	at android.widget.Editor.updateFloatingToolbarVisibility(Editor.java:1554)
	at android.widget.Editor.onTouchEvent(Editor.java:1501)
	at android.widget.TextView.onTouchEvent(TextView.java:10105)
	at android.view.View.dispatchTouchEvent(View.java:10920)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:696)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:623)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1914)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:585)
	at android.view.View.dispatchPointerEvent(View.java:11149)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5222)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5071)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4628)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4594)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4731)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4602)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4628)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4594)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4602)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4575)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7205)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7137)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7098)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7316)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7279)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:634)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by Thewisem** [comment]
Here is a log of when it happens

**Comment by n8fr8** [comment]
Thanks for the log, though it doesn't really help clarify why this is happening, as the crash is deep within the Android UI code. We aren't doing anything custom or abnormal with our custom bridge user interface.

**Comment by n8fr8** [comment]
Please test our latest beta:
https://github.com/guardianproject/orbot/releases/tag/16.5.1-BETA-2a-tor.0.4.5.9

**Comment by Thewisem** [comment]
This is somewhat worse as when I started orbot, it crashed

**Comment by Thewisem** [comment]
But custom bridges is working

**Comment by sisbell** [comment]
Copy-Paste breaking on Samsung devices is a known issue. 

https://issuetracker.google.com/issues/37127697

From the google issue tracker:

- Workround: User can use S pen instead
- Fix: Disable copy-paste on Samsung devices

**Comment by Thewisem** [comment]
How do you disable copy paste

**Comment by Thewisem** [comment]
And can you fix this issue?

**Comment by sisbell** [comment]
To fix this issue, would require disabling copy-paste feature in the app for all Samsung devices. This fixes the crash (which is good) but functionality is still missing.

Are you trying this from "Request Bridges from TorProject" or doing a copy/paste from the website?

Does the request-by-email work for you? I tried it on my Pixel and the email leaves out text and body messages for the request so its broken for me. I believe it's also broken for Samsung devices. I opened issue #505 for that.

**Comment by bitmold** [comment]
Closing because users can paste bridges and the UI where this was crashing no longer exists in app. In my testing on Samsung devices I haven't seen this in any recent memory.
