### ISSUE TITLE
error creating FileDescriptor, causes Orbot to hang on start

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-android#664]
2022-04-21 09:52:41.289 22416-22476/org.torproject.android W/System.err: java.io.IOException: /data/user/0/org.torproject.android/app_TorService/data/ControlSocket open: Connection refused
2022-04-21 09:52:41.289 22416-22476/org.torproject.android W/System.err:     at org.torproject.jni.TorService.prepareFileDescriptor(Native Method)
2022-04-21 09:52:41.289 22416-22476/org.torproject.android W/System.err:     at org.torproject.jni.TorService.access$300(TorService.java:43)
2022-04-21 09:52:41.289 22416-22476/org.torproject.android W/System.err:     at org.torproject.jni.TorService$2.run(TorService.java:272)

**Comment by n8fr8** [comment]
This happens even without a native code crash first

**Comment by n8fr8** [comment]
this also triggers the endless "waiting for lock", and requires a force stop to resolve

**Comment by medvedev125** [comment]
Hello. I faced a similar problem (unfortunately Logs were not saved): orbot to hang on start.
Moreover: uninstalling Orbot and installing it again did not help.
The problem was solved only after reinstalling TorBrowser along with Orbot.

**Comment by n8fr8** [comment]
Tor Browser and Orbot have no connection at all, and run entirely separate version of tor. Not sure how it could have solved the problem.
